<?php

namespace AppBundle\Repository;

/**
 * LaboratoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LaboratoryRepository extends \Doctrine\ORM\EntityRepository
{
}
